Repository modern-agile-team/yeoreum-front-client, pull requests merged in 2023-02, with the labels that each got.

#51 feature/ujin/#40: 타인 프로필 UI 구현
  yeoreum/package-lock.json
  yeoreum/package.json
  yeoreum/src/components/chatting/chattingLists/ParticipantsList.tsx
  yeoreum/src/components/common/Modal.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/components/editProfile/ModalContent.tsx
  yeoreum/src/components/elseProfile/DuelModal.tsx
  yeoreum/src/components/elseProfile/ElseProfile.tsx
Labels: 🤬fix, 🗃package, 🎨publish

#59 Feature/ujin/#58: 친구 신청 개발 이슈로 인한 pr
  yeoreum/src/components/common/Modal.tsx
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/applicationModal/AllUserSearch.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/FriendTop.tsx
  yeoreum/src/components/friend/page/MyFriendList.tsx
  yeoreum/src/components/friend/page/UserSearch.tsx
  yeoreum/src/pages/friend/index.tsx
  yeoreum/src/types/friend.ts
Labels: 🤬fix

#66 Feature/ujin/#64: 타인프로필 반응형 UI 구현
  yeoreum/src/components/board/create/AddPartyMembers.tsx
  yeoreum/src/components/common/Modal.tsx
  yeoreum/src/components/elseProfile/ElseProfile.tsx
Labels: 🎨publish

#68 Feature/ujin/#67: theme css 적용
  yeoreum/src/components/chatting/Container.tsx
  yeoreum/src/components/chatting/chatting/ChattingBox.tsx
  yeoreum/src/components/chatting/chatting/ChattingContent.tsx
  yeoreum/src/components/chatting/chatting/ChattingInput.tsx
  yeoreum/src/components/chatting/chattingLists/ChatList.tsx
  yeoreum/src/components/chatting/chattingLists/ChattingListsBox.tsx
  yeoreum/src/components/chatting/chattingLists/ParticipantsList.tsx
  yeoreum/src/components/editProfile/EditInfo.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/components/editProfile/ModalContent.tsx
  yeoreum/src/components/elseProfile/DuelModal.tsx
  yeoreum/src/components/elseProfile/ElseProfile.tsx
  yeoreum/src/components/friend/addModal/AddFriendModal.tsx
  yeoreum/src/components/friend/addModal/MyFriendList.tsx
  yeoreum/src/components/friend/addModal/MyFriendSearch.tsx
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/applicationModal/AllUserSearch.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/MyFriendList.tsx
  yeoreum/src/components/friend/page/UserSearch.tsx
  yeoreum/src/components/myPage/Lists.tsx
  yeoreum/src/components/myPage/Profile.tsx
  yeoreum/src/components/myPage/Rating.tsx
  yeoreum/src/styles/theme.ts
Labels: 🖍css, 🛠refactor

#71 Feature/donkey/#70: 아이콘, 이미지 파일 추가
  yeoreum/public/anonymous.png
  yeoreum/public/icons/arrowleft.svg
  yeoreum/public/icons/arrowright.svg
  yeoreum/public/icons/clipboard.svg
  yeoreum/public/icons/clock.svg
  yeoreum/public/icons/heart.svg
  yeoreum/public/icons/heartfilled.svg
  yeoreum/public/icons/location.svg
  yeoreum/public/icons/logout.svg
  yeoreum/public/icons/man.svg
  yeoreum/public/icons/message.svg
  yeoreum/public/icons/more.svg
  yeoreum/public/icons/notification.svg
  yeoreum/public/icons/paperclip.svg
  yeoreum/public/icons/people.svg
  yeoreum/public/icons/personalcard.svg
  yeoreum/public/icons/searchnormal.svg
  yeoreum/public/icons/star.svg
  yeoreum/public/icons/user.svg
  yeoreum/public/icons/useradd.svg
  yeoreum/public/icons/users.svg
  yeoreum/public/icons/usersearch.svg
  yeoreum/public/icons/woman.svg
Labels: 🚎file

#72 Feature/ujin/#69: 전역 상태, 데이터 패칭 라이브러리 초기 세팅
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/FriendTop.tsx
  yeoreum/src/pages/_app.tsx
  yeoreum/src/store/hooks.ts
  yeoreum/src/store/modules/modal.ts
  yeoreum/src/store/store.tsx
Labels: ✨feat

#73 Feature/donkey/#49: 게시글 전체 조회 기능 구현
  yeoreum/src/components/Nav/Nav.tsx
  yeoreum/src/components/Nav/NavBar.tsx
  yeoreum/src/components/UserModal/UserModal.tsx
  yeoreum/src/components/board/PostList.tsx
  yeoreum/src/types/post.ts
  yeoreum/src/utils/postStatus.ts
  yeoreum/src/utils/sliceString.ts
  yeoreum/src/utils/user.ts
Labels: 🖍css, ✨feat, 🚎file

#75 Feature/donkey/#60: Nav 디자인 변경 적용
  yeoreum/next.config.js
  yeoreum/public/anonymous.png
  yeoreum/public/logo.png
  yeoreum/src/components/Nav/Nav.tsx
  yeoreum/src/components/Nav/NavBar.tsx
  yeoreum/src/components/UserModal/UserModal.tsx
  yeoreum/src/components/alarm/Alarm.tsx
Labels: ✨feat, 🚎file

#76 Feature/bang/#61: 자체로그인 회원가입 리팩토링, 회원가입 상세 정보 페이지 퍼블리싱
  yeoreum/src/components/login/loginForm.tsx
  yeoreum/src/components/service/inquiry/InquiryForm.tsx
  yeoreum/src/components/signUp/Form.tsx
  yeoreum/src/components/signUp/signUpBody.tsx
  yeoreum/src/components/signUp/signUpContainer.tsx
  yeoreum/src/components/signUp/signUpForm.tsx
  yeoreum/src/components/signUp/signUpFormStyle.tsx
  yeoreum/src/components/signUp/signUpHeader.tsx
  yeoreum/src/components/signUp/signUpProfileForm.tsx
  yeoreum/src/constants/signUpConst.ts
  yeoreum/src/hooks/useForm.ts
  yeoreum/src/pages/signup/index.tsx
  yeoreum/src/pages/signup/profile/[userNo].tsx
  yeoreum/src/types/common.ts
  yeoreum/src/types/signUp.ts
Labels: ✨feat, 🛠refactor, 🎨publish

#81 Feature/ujin/#56: 친구페이지 조회 및 검색 구현
  yeoreum/package-lock.json
  yeoreum/package.json
  yeoreum/src/api/friendPage.ts
  yeoreum/src/api/myPage.ts
  yeoreum/src/components/common/LoadingSpinner.tsx
  yeoreum/src/components/common/ProfileImage.tsx
  yeoreum/src/components/elseProfile/ElseProfile.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/FriendTop.tsx
  yeoreum/src/components/friend/page/MyFriendList.tsx
  yeoreum/src/components/friend/page/UserSearch.tsx
  yeoreum/src/components/myPage/Profile.tsx
  yeoreum/src/pages/friend/index.tsx
  yeoreum/src/types/friend.ts
  yeoreum/src/types/user.ts
Labels: 🖍css, ✨feat, 🤬fix, 🎨publish

#83 Feature/donkey/#78: 알림 모달 및 페이지 리팩토링 및 기능 구현
  yeoreum/src/api/notices.ts
  yeoreum/src/components/alarm/Alarm.tsx
  yeoreum/src/components/alarm/AlarmList.tsx
  yeoreum/src/components/alarm/AlarmListItem.tsx
  yeoreum/src/components/nav/Nav.tsx
  yeoreum/src/components/nav/NavBar.tsx
  yeoreum/src/components/notifications/Notification.tsx
  yeoreum/src/components/notifications/NotificationList.tsx
  yeoreum/src/hooks/queries/notices.ts
  yeoreum/src/utils/sliceString.ts
Labels: ✨feat, 🛠refactor

#84 Feature/ujin/#82: 마이페이지 기능 구현 및 계정 설정 반응형 수정
  yeoreum/src/api/myPage.ts
  yeoreum/src/components/board/PostList.tsx
  yeoreum/src/components/common/ProfileImage.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/components/myPage/Lists.tsx
  yeoreum/src/components/myPage/Profile.tsx
  yeoreum/src/types/post.ts
Labels: 🖍css, ✨feat

#86 Feature/ujin/#85: 유저 검색 후 친구 신청 구현
  yeoreum/src/api/friendPage.ts
  yeoreum/src/api/myPage.ts
  yeoreum/src/apis/friends.ts
  yeoreum/src/apis/hello.ts
  yeoreum/src/apis/notices.ts
  yeoreum/src/apis/users.ts
  yeoreum/src/components/editProfile/ModalContent.tsx
  yeoreum/src/components/elseProfile/ElseProfile.tsx
  yeoreum/src/components/friend/addModal/AddFriendModal.tsx
  yeoreum/src/components/friend/addModal/MyFriendList.tsx
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/applicationModal/AllUserSearch.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/MyFriendList.tsx
  yeoreum/src/components/friend/page/UserSearch.tsx
  yeoreum/src/components/myPage/Profile.tsx
  yeoreum/src/components/nav/Nav.tsx
  yeoreum/src/hooks/queries/notices.ts
  yeoreum/src/pages/friend/index.tsx
  yeoreum/src/types/user.ts
Labels: ✨feat, 🛠refactor

#95 Feature/donkey/#91: 게시글 작성 기능 구현
  yeoreum/public/icons/check.svg
  yeoreum/src/apis/friends.ts
  yeoreum/src/apis/posts.ts
  yeoreum/src/components/board/create/AddPartyMembers.tsx
  yeoreum/src/components/board/create/CustomDropDown.tsx
  yeoreum/src/components/board/create/PostGender.tsx
  yeoreum/src/components/board/create/PostInput.tsx
  yeoreum/src/components/board/create/SubmitButton.tsx
  yeoreum/src/components/friend/addModal/AddFriendModal.tsx
  yeoreum/src/components/friend/addModal/MyFriendList.tsx
  yeoreum/src/components/friend/addModal/MyFriendSearch.tsx
  yeoreum/src/hooks/queries/posts.ts
  yeoreum/src/pages/board/create.tsx
  yeoreum/src/types/post.ts
Labels: 🖍css, ✨feat, 🛠refactor

#93 Feature/ujin/#87: 계정 설정 구현
  yeoreum/src/apis/users.ts
  yeoreum/src/components/editProfile/EditInfo.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/components/editProfile/MajorChange.tsx
  yeoreum/src/components/editProfile/ModalContent.tsx
  yeoreum/src/components/myPage/Profile.tsx
Labels: ✨feat

#102 Feature/ujin/#94: 채팅 소켓 초기화
  yeoreum/package-lock.json
  yeoreum/package.json
  yeoreum/public/icons/send.svg
  yeoreum/src/apis/chats.ts
  yeoreum/src/components/chatting/chatting/ChattingBox.tsx
  yeoreum/src/components/chatting/chatting/ChattingContent.tsx
  yeoreum/src/components/chatting/chatting/ChattingInput.tsx
  yeoreum/src/components/chatting/chattingLists/ChatList.tsx
  yeoreum/src/components/chatting/chattingLists/ChattingListsBox.tsx
  yeoreum/src/components/chatting/chattingLists/ParticipantsList.tsx
  yeoreum/src/pages/_app.tsx
  yeoreum/src/pages/chatting/index.tsx
  yeoreum/src/types/chat.ts
Labels: ✨feat

#105 Feature/ujin/#104: 계정 설정 accessToken 재발급
  yeoreum/src/apis/config.ts
  yeoreum/src/apis/friends.ts
  yeoreum/src/apis/users.ts
  yeoreum/src/components/editProfile/EditInfo.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/components/editProfile/MajorChange.tsx
  yeoreum/src/components/editProfile/ModalContent.tsx
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/myPage/Lists.tsx
  yeoreum/src/components/myPage/Profile.tsx
  yeoreum/src/hooks/queries/users.ts
  yeoreum/src/pages/friend/index.tsx
Labels: ✨feat, 🛠refactor

#108 Feature/ujin/#103: 채팅 대화 내용 구현
  yeoreum/src/apis/chats.ts
  yeoreum/src/components/chatting/chatting/ChattingBox.tsx
  yeoreum/src/components/chatting/chatting/ChattingContent.tsx
  yeoreum/src/components/chatting/chatting/ChattingInput.tsx
  yeoreum/src/components/chatting/chattingLists/ChatList.tsx
  yeoreum/src/components/chatting/chattingLists/ChattingListsBox.tsx
  yeoreum/src/components/chatting/chattingLists/ParticipantsList.tsx
  yeoreum/src/components/editProfile/EditProfile.tsx
  yeoreum/src/hooks/queries/chat.ts
  yeoreum/src/pages/chatting/index.tsx
  yeoreum/src/types/chat.ts
Labels: ✨feat

#114 Feature/ujin/#109: 친구 페이지 보낸 신청, 받은 신청 구현
  yeoreum/src/apis/friends.ts
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/applicationModal/ApplicationFriendModal.tsx
  yeoreum/src/components/friend/page/FriendList.tsx
  yeoreum/src/components/friend/page/FriendMain.tsx
  yeoreum/src/components/friend/page/MyFriendList.tsx
  yeoreum/src/hooks/queries/friends.ts
  yeoreum/src/pages/friend/index.tsx
  yeoreum/src/types/friend.ts
Labels: ✨feat

#116 Feature/donkey/#113: axios 요청 인스턴스로 변경
  yeoreum/src/apis/notices.ts
  yeoreum/src/apis/notices/boardRequestHandling.ts
  yeoreum/src/apis/notices/chatRequestHandling.ts
  yeoreum/src/apis/notices/friendRequestHandling.ts
  yeoreum/src/apis/posts.ts
  yeoreum/src/components/alarm/Alarm.tsx
  yeoreum/src/components/alarm/AlarmList.tsx
  yeoreum/src/components/alarm/AlarmListItem.tsx
  yeoreum/src/components/board/create/AddPartyMembers.tsx
  yeoreum/src/components/notifications/Notification.tsx
  yeoreum/src/components/notifications/NotificationList.tsx
  yeoreum/src/hooks/queries/notices.ts
  yeoreum/src/hooks/queries/notices/boardRequestHandling.ts
  yeoreum/src/hooks/queries/notices/chatRequestHandling.ts
  yeoreum/src/hooks/queries/notices/friendRequestHandling.ts
  yeoreum/src/hooks/queries/posts.ts
  yeoreum/src/pages/apply/[postNo]/application/[applicationNo].tsx
  yeoreum/src/pages/board/index.tsx
  yeoreum/src/utils/noticeDataByType.ts
Labels: 🛠refactor

#118 Feature/ujin/#112: 타인프로필 친구 신청 버튼 다르게 보이게 구현
  yeoreum/src/apis/friends.ts
  yeoreum/src/components/elseProfile/ElseProfile.tsx
  yeoreum/src/components/friend/applicationModal/AllUserList.tsx
  yeoreum/src/components/friend/page/FriendList.tsx
  yeoreum/src/hooks/queries/friends.ts
  yeoreum/src/types/friend.ts
Labels: ✨feat

#121 Feature/ujin/#119: 계정 설정 닉네임, 소개 수정 제한 걸기, 학과 수정중일때 에러 처리
  yeoreum/src/apis/users.ts
  yeoreum/src/components/editProfile/EditInfo.tsx
  yeoreum/src/components/editProfile/MajorChange.tsx
  yeoreum/src/hooks/queries/users.ts
Labels: ✨feat

#122 Feature/ujin/#115: 채팅 대화 길어질때 최신 메세지로 포커스
  yeoreum/src/components/chatting/chatting/ChattingBox.tsx
  yeoreum/src/components/chatting/chatting/ChattingContent.tsx
  yeoreum/src/components/chatting/chatting/ChattingInput.tsx
  yeoreum/src/components/chatting/chattingLists/ChatList.tsx
  yeoreum/src/pages/chatting/index.tsx
Labels: ✨feat

#124 Feature/ujin/#120: 마이페이지 북마크 가져오기
  yeoreum/src/apis/users.ts
  yeoreum/src/components/myPage/Lists.tsx
  yeoreum/src/hooks/queries/users.ts
Labels: ✨feat
